{% set name = "docker-buildx" %}
{% set version = "0.19.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/docker/buildx/archive/v{{ version }}.tar.gz
  sha256: 7a14199d052d4933bb5379207f13d4b6562ab10f3fb9f5217790b482bd2b25f4

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - docker-buildx --help

about:
  home: https://github.com/docker/buildx
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Docker CLI plugin for extended build capabilities with BuildKit
  dev_url: https://github.com/docker/buildx

extra:
  recipe-maintainers:
    - danielnachun
