{% set name = "docker-buildx" %}
{% set version = "0.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/docker/buildx/archive/v{{ version }}.tar.gz
  sha256: e5a7573a5995c0f12c86d35a8148b2a10a6f1b11d1cf8c6977bf03ac281e6959

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - docker-buildx --help

about:
  home: https://github.com/docker/buildx
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Docker CLI plugin for extended build capabilities with BuildKit
  dev_url: https://github.com/docker/buildx

extra:
  recipe-maintainers:
    - danielnachun
