{% set name = "docker-buildx" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/docker/buildx/archive/v{{ version }}.tar.gz
  sha256: eab1eb18e06873c64ff1a0df00b298bcdbfd9c9515debbbac85b4c2cd0b228ff

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - docker-buildx --help

about:
  home: https://github.com/docker/buildx
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Docker CLI plugin for extended build capabilities with BuildKit
  dev_url: https://github.com/docker/buildx

extra:
  recipe-maintainers:
    - danielnachun
