{% set name = "docker-buildx" %}
{% set version = "0.19.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/docker/buildx/archive/v{{ version }}.tar.gz
  sha256: 981a17d5763d9583c6c73ac194d4978de6fb632e3818fa6d983aefbc0c02f844

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - docker-buildx --help

about:
  home: https://github.com/docker/buildx
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Docker CLI plugin for extended build capabilities with BuildKit
  dev_url: https://github.com/docker/buildx

extra:
  recipe-maintainers:
    - danielnachun
