{% set name = "docker-buildx" %}
{% set version = "0.30.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/docker/buildx/archive/v{{ version }}.tar.gz
  sha256: 8acfd78fc74ad79d674f6305c7eb62807f592946a76e9a0451f944f74fc75e33

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - docker-buildx --help

about:
  home: https://github.com/docker/buildx
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Docker CLI plugin for extended build capabilities with BuildKit
  dev_url: https://github.com/docker/buildx

extra:
  recipe-maintainers:
    - danielnachun
