schema_version: 1

context:
  version: "0.37.1"

package:
  name: docker-buildx
  version: ${{ version }}

source:
  url: https://github.com/docker/buildx/archive/v${{ version }}.tar.gz
  sha256: c8eb34392910bf18a858d4099e841deec2f7ea433bb3ed230082f55b69f19118

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - docker-buildx --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Docker CLI plugin for extended build capabilities with BuildKit
  homepage: https://github.com/docker/buildx
  repository: https://github.com/docker/buildx

extra:
  recipe-maintainers:
    - danielnachun
