schema_version: 1

context:
  version: "0.33.0"

package:
  name: docker-buildx
  version: ${{ version }}

source:
  url: https://github.com/docker/buildx/archive/v${{ version }}.tar.gz
  sha256: 00b5d5093f6b6cb75fd687988fb395253d10a5ca4d7e4c6b26af3914c219d2d7

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - docker-buildx --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Docker CLI plugin for extended build capabilities with BuildKit
  homepage: https://github.com/docker/buildx
  repository: https://github.com/docker/buildx

extra:
  recipe-maintainers:
    - danielnachun
