schema_version: 1

context:
  version: "0.38.0"

package:
  name: docker-buildx
  version: ${{ version }}

source:
  url: https://github.com/docker/buildx/archive/v${{ version }}.tar.gz
  sha256: f4705415fe4e011f19c6fe0fa324fef81236791815c51bb6210b3bbbca5b1319

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - docker-buildx --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Docker CLI plugin for extended build capabilities with BuildKit
  homepage: https://github.com/docker/buildx
  repository: https://github.com/docker/buildx

extra:
  recipe-maintainers:
    - danielnachun
